### ISSUE TITLE
new feature proposition

### ISSUE THREAD

**Issue by ah584d** [kyaido/eslint-plugin-literal-blacklist#13]
Hi , let's say that i have in my code the following snippet:
```
if (appearance === 'dark') {
     source = require('assets/darkModeAssetBlabla.something');
 }
```
and I would like to exclude the term "dark", so I implemented the following rule:
```
'literal-blacklist/literal-blacklist': [
      ERROR,
      [
        {
          term: "=== 'dark'",
          message: "use ThemeModes.DARK instead of 'dark'",
          ignoreCase: true,
        },
      ],
    ],
```
what will happens is that both 'dark' and 'darkModeAssetBlabla.something' will be underlined by eslint, while I want to target exclusively entire words.

Can you add the option, after ignoreCase, matchWholeWord?
I think it will make senses
thanks

**Comment by kyaido** [comment]
@ah584d 
I am sorry for the delay in response.

I have modified it to accept regular expression.
Please update to version 1.2.0.
You can specify `term:"^dark$"`.
